name: titanic
channels:
  - defaults
  - conda-forge 
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib=3.4
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn
  - tensorflow-gpu=2.4
  - pip:
    - pydot
    - graphviz
    - imblearn
    - imbalanced-learn
    - ipywidgets
    - shap
    - diffprivlib
    - optuna
    - plotly
    - kaleido
    - xgboost
