name: titanic
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib=3.4
  - numpy=1.20
  - pandas=1.3
  - pip=21.1
  - python=3.8
  - scikit-learn==0.24
  - tensorflow==2.4
  - pip:
    - pydot==1.4
    - graphviz==0.17
    - imblearn==0.0
  

