name: titanic
channels:
  - defaults
dependencies:
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.6
  - pytorch==1.4.0
  - scikit-learn==0.22.1
  - scipy==1.4.1
  - tensorflow==2.1.0
  

