name: titanic
channels:
  - defaults
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip=21.1
  - python=3.8
  - scikit-learn
  - tensorflow=2.4
  - pip:
    - pydot
    - graphviz
    - imblearn
    - imbalanced-learn
    - shap
    - diffprivlib
    - optuna
  

