name: titanic
channels:
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn
  - tensorflow-gpu=2.4
  - tensorflow-estimator=2.4
  - pip:
    - pydot
    - graphviz
    - imblearn
    - imbalanced-learn
    - ipywidgets
    - shap
    - diffprivlib
    - optuna
    - plotly
    - kaleido
  

